Controller: Don't pass encoded dimensions to `addParams()`
Icinga/icingaweb2-module-cube pull request #151
Opened 2023-08-15 07:43 UTC by sukhwinder33445

fixes #146 
fixes #149

2023-08-15 10:24 UTC, yhabteab requested changes

2023-08-15 10:24 UTC, yhabteab commented on library/Cube/Web/Controller.php
> +        }
What about the other view url params? I think it makes sense to decode all params and not just `dimensions`. Please also use `rawurldecode()` instead.

2023-08-16 10:41 UTC, yhabteab approved these changes

2023-09-01 12:08 UTC, nilmerg commented
Superseded by #157

2023-09-01 12:08 UTC, closed without merging