Allows grouping of services according to host custom variables
Icinga/icingaweb2-module-cube pull request #97
Opened 2022-12-01 12:37 UTC by sukhwinder33445

2022-12-06 15:45 UTC, nilmerg requested changes

2022-12-06 15:45 UTC, nilmerg commented on library/Cube/IcingaDb/CustomVariableDimension.php
> +    /** @var string|null variable source name */
`?string` please

2022-12-06 15:45 UTC, nilmerg commented on library/Cube/IcingaDb/IcingaDbHostStatusCube.php
> +    public static function fetchHostDimensions(IcingaDbCube $cube): array
please make this non-static and put it in `IcingaDbCube` (Rename it then to `fetchHostVariableDimensions()`)

2022-12-06 15:45 UTC, nilmerg commented on library/Cube/ProvidedHook/Cube/IcingaDbActions.php
> +            if (strpos($dimension, '.vars.') === false) {
This leads to false positives if a custom var contains `.vars.`. Don't use strpos.

2022-12-08 08:58 UTC, nilmerg requested changes

2022-12-08 08:58 UTC, nilmerg commented on library/Cube/IcingaDb/IcingaDbCube.php
> +            $name = preg_replace('/\\[\d+](?=\\.|$)/', '[*]', $row->customvar_flat->flatname);
Please lower the name, custom vars are handled case-insensitive by Icinga DB Web.

2022-12-08 08:58 UTC, nilmerg commented on library/Cube/IcingaDb/IcingaDbCube.php
> +            $name = preg_replace('/\\[\d+](?=\\.|$)/', '[*]', $row->customvar_flat->flatname);
Please lowercase this as well.

2022-12-08 08:58 UTC, nilmerg commented on library/Cube/IcingaDb/CustomVariableDimension.php
> +        if (count($result = explode('.vars.', $name)) === 2) {
This may also lead to false positives if the customvar itself contains `.vars.`. Consider splitting this by a regex.

2022-12-12 10:18 UTC, nilmerg requested changes

2022-12-12 10:19 UTC, nilmerg commented on library/Cube/IcingaDb/CustomVariableDimension.php
> +        if (preg_match('/^(host|service).vars.(.*)/', $name, $matches) && ! empty($matches)) {
Oh and, the ! empty check is redundant. If the expression doesn't match anything, preg_match returns 0.

2022-12-13 15:11 UTC, nilmerg approved these changes

2022-12-29 11:06 UTC, lippserd approved these changes

2022-12-29 11:06 UTC, merged